-- EXECUTION ORDER: Run this file third (after insert_positions.sql)
USE nfl_stats;

INSERT INTO teams (team_name, city, conference, division) VALUES
('Bills', 'Buffalo', 'AFC', 'East'),
('Dolphins', 'Miami', 'AFC', 'East'),
('Patriots', 'New England', 'AFC', 'East'),
('Jets', 'New York', 'AFC', 'East'),
('Ravens', 'Baltimore', 'AFC', 'North'),
('Bengals', 'Cincinnati', 'AFC', 'North'),
('Browns', 'Cleveland', 'AFC', 'North'),
('Steelers', 'Pittsburgh', 'AFC', 'North'),
('Texans', 'Houston', 'AFC', 'South'),
('Colts', 'Indianapolis', 'AFC', 'South'),
('Jaguars', 'Jacksonville', 'AFC', 'South'),
('Titans', 'Tennessee', 'AFC', 'South'),
('Broncos', 'Denver', 'AFC', 'West'),
('Chiefs', 'Kansas City', 'AFC', 'West'),
('Raiders', 'Las Vegas', 'AFC', 'West'),
('Chargers', 'Los Angeles', 'AFC', 'West'),
('Cowboys', 'Dallas', 'NFC', 'East'),
('Giants', 'New York', 'NFC', 'East'),
('Eagles', 'Philadelphia', 'NFC', 'East'),
('Commanders', 'Washington', 'NFC', 'East'),
('Bears', 'Chicago', 'NFC', 'North'),
('Lions', 'Detroit', 'NFC', 'North'),
('Packers', 'Green Bay', 'NFC', 'North'),
('Vikings', 'Minnesota', 'NFC', 'North'),
('Falcons', 'Atlanta', 'NFC', 'South'),
('Panthers', 'Carolina', 'NFC', 'South'),
('Saints', 'New Orleans', 'NFC', 'South'),
('Buccaneers', 'Tampa Bay', 'NFC', 'South'),
('Cardinals', 'Arizona', 'NFC', 'West'),
('Rams', 'Los Angeles', 'NFC', 'West'),
('49ers', 'San Francisco', 'NFC', 'West'),
('Seahawks', 'Seattle', 'NFC', 'West');